In [1]:
import numpy as np
import pandas as pd

# Creating a DataFrame

In [3]:
data = {
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [9]:
columns = ["Name", "Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### Selection and indexing of Columns

In [10]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [11]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [ ]:
df[["Name","City"]]  # for this we can select the columns of the from the table

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### creating a new column

In [20]:
df2["Designation"] = ["Doctor", "Eng.","Doctor","Eng."]

In [14]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

### Removing columns

In [21]:
df2.drop('Designation',axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [23]:
df2.drop('Designation',axis =1, inplace= True) # inplace is used to delete it . Also if we make the axis to 0 it will remove it horizontally means entire row will be deleted

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2.drop(0,axis =0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

### Selecting rows

In [26]:
df2.loc[[0,1]]  # loc = location and we hav passes multiple one means two index 0 and 1 so that we have using the [] inside to pass hte multiple value

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [27]:
df.iloc[3] # index location. Its same as normal loc as well

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### Selecting Subsets of Rows and columns

In [28]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [29]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

### conditional Selection

In [30]:
# I want to see only those people who age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [32]:
# age > 30 & people is from paris
df2[(df2["Age"]>30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000